config/routes.rb
Rails.application.routes.draw do
  
  resources :cards do
    collection do
      post 'register_card'
      post 'register_bank_account'
      get 'by_user'
      post 'delete_card'
    end
    member do
      post 'activate'
    end
  end

  resources :registered_anomaly_statuses

  resources :registered_anomalies do
    collection do
      post 'from_student'
      post 'from_tutor'
      post 'assign'
      post 'assign_other'
      post 'reject'
    end
  end

  resources :anomalies

  resources :municipalities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :specific_availabilities

  resources :availabilities

  resources :week_days

  resources :vacations

  resources :preferences

  resources :appointment_statuses

  resources :appointments do
    collection do
      get 'by_tutor'
      get 'by_student'
    end
    member do
      post 'change_status'
      post 'force_charge'
      post 'force_pay'
    end
  end

  resources :messages do
    collection do
      get 'conversations'
      get 'by_conversation'
      get 'pending_conversations'
      post 'mark_read'
    end
  end

  resources :reviews do
    collection do
      get 'by_tutor'
    end
    member do
      post 'activate'
    end
  end

  resources :bank_accounts

  resources :categories

  resources :purchases

  resources :addresses

  resources :banks

  resources :states

  resources :cities

  resources :postal_codes

  resources :counties do
    collection do
      get 'find_for_autocomplete'
    end
  end

  resources :students do
    collection do
      get 'profile'
      post 'remember_tutor'
    end
  end

  resources :tutors do
    collection do
      get 'by_county_and_category_ids'
      match 'by_query_params_for_google', :via => [:get, :post]
      get 'profile'
      get 'status'
      get 'by_student'
      get 'balance'
      post 'cash_out'
    end
    member do
      get 'info'
      get 'availability_list'
      get 'ranged_availability_list'
      match 'request_class', :via => [:get, :post]
      match 'save_availabilities', :via => [:get, :post]
      match 'save_specific_availabilities', :via => [:get, :post]
    end
  end

  resources :roles

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords"}
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
    get 'signin', :to => "devise/sessions#new"
    get 'signup', :to => "devise/registrations#new"
  end
  resources :users

  get "counties_all" => "counties#find_for_autocomplete", :as => :find_for_autocomplete

  get "tutor" => "tutor_display#landing", :as => :tutor_landing
  
  get "tutor_redirect" => "tutor_display#redirect", :as => :tutor_redirect

  get "student" => "student_display#landing", :as => :student_landing

  get "tutor_dashboard" => "dashboard#by_tutor", :as => :tutor_dashboard

  get "student_dashboard" => "dashboard#by_student", :as => :student_dashboard

  get "tutor_profile" => "student_display#profile", :as => :tutor_profile
  root 'student_display#landing'

end

app/models/anomaly.rb
class Anomaly < ActiveRecord::Base
  has_many :registered_anomalies
end

app/controllers/anomalies_controller.rb
class AnomaliesController < InheritedResources::Base
  load_and_authorize_resource
end

app/helpers/anomalies_helper.rb
module AnomaliesHelper
end

app/views/anomalies/_form.html.erb
<%= form_for(@anomaly) do |f| %>
  <% if @anomaly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anomaly.errors.count, "error") %> prohibited this anomaly from being saved:</h2>

      <ul>
      <% @anomaly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anomalies/edit.html.erb
<h1>Editing anomaly</h1>

<%= render 'form' %>

<%= link_to 'Show', @anomaly %> |
<%= link_to 'Back', anomalies_path %>

app/views/anomalies/index.html.erb
<h1>Listing anomalies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anomalies.each do |anomaly| %>
      <tr>
        <td><%= anomaly.name %></td>
        <td><%= link_to 'Show', anomaly %></td>
        <td><%= link_to 'Edit', edit_anomaly_path(anomaly) %></td>
        <td><%= link_to 'Destroy', anomaly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anomaly', new_anomaly_path %>

app/views/anomalies/new.html.erb
<h1>New anomaly</h1>

<%= render 'form' %>

<%= link_to 'Back', anomalies_path %>

app/views/anomalies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @anomaly.name %>
</p>

<%= link_to 'Edit', edit_anomaly_path(@anomaly) %> |
<%= link_to 'Back', anomalies_path %>