config/routes.rb
Rails.application.routes.draw do
  
  resources :cards do
    collection do
      post 'register_card'
      post 'register_bank_account'
      get 'by_user'
      post 'delete_card'
    end
    member do
      post 'activate'
    end
  end

  resources :registered_anomaly_statuses

  resources :registered_anomalies do
    collection do
      post 'from_student'
      post 'from_tutor'
      post 'assign'
      post 'assign_other'
      post 'reject'
    end
  end

  resources :anomalies

  resources :municipalities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :specific_availabilities

  resources :availabilities

  resources :week_days

  resources :vacations

  resources :preferences

  resources :appointment_statuses

  resources :appointments do
    collection do
      get 'by_tutor'
      get 'by_student'
    end
    member do
      post 'change_status'
      post 'force_charge'
      post 'force_pay'
    end
  end

  resources :messages do
    collection do
      get 'conversations'
      get 'by_conversation'
      get 'pending_conversations'
      post 'mark_read'
    end
  end

  resources :reviews do
    collection do
      get 'by_tutor'
    end
    member do
      post 'activate'
    end
  end

  resources :bank_accounts

  resources :categories

  resources :purchases

  resources :addresses

  resources :banks

  resources :states

  resources :cities

  resources :postal_codes

  resources :counties do
    collection do
      get 'find_for_autocomplete'
    end
  end

  resources :students do
    collection do
      get 'profile'
      post 'remember_tutor'
    end
  end

  resources :tutors do
    collection do
      get 'by_county_and_category_ids'
      match 'by_query_params_for_google', :via => [:get, :post]
      get 'profile'
      get 'status'
      get 'by_student'
      get 'balance'
      post 'cash_out'
    end
    member do
      get 'info'
      get 'availability_list'
      get 'ranged_availability_list'
      match 'request_class', :via => [:get, :post]
      match 'save_availabilities', :via => [:get, :post]
      match 'save_specific_availabilities', :via => [:get, :post]
    end
  end

  resources :roles

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords"}
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
    get 'signin', :to => "devise/sessions#new"
    get 'signup', :to => "devise/registrations#new"
  end
  resources :users

  get "counties_all" => "counties#find_for_autocomplete", :as => :find_for_autocomplete

  get "tutor" => "tutor_display#landing", :as => :tutor_landing
  
  get "tutor_redirect" => "tutor_display#redirect", :as => :tutor_redirect

  get "student" => "student_display#landing", :as => :student_landing

  get "tutor_dashboard" => "dashboard#by_tutor", :as => :tutor_dashboard

  get "student_dashboard" => "dashboard#by_student", :as => :student_dashboard

  get "tutor_profile" => "student_display#profile", :as => :tutor_profile
  root 'student_display#landing'

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
	belongs_to :tutor
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  load_and_authorize_resource

  before_action :set_vacation, only: [:show, :edit, :update, :destroy]

  # GET /vacations
  # GET /vacations.json
  def index
    @vacations = Vacation.all
  end

  # GET /vacations/1
  # GET /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
  end

  # POST /vacations
  # POST /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to @vacation, notice: 'Vacation was successfully created.' }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacations/1
  # PATCH/PUT /vacations/1.json
  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to @vacation, notice: 'Vacation was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1
  # DELETE /vacations/1.json
  def destroy
    @vacation.destroy
    respond_to do |format|
      format.html { redirect_to vacations_url, notice: 'Vacation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_params
      params.require(:vacation).permit(:start, :end, :tutor_id)
    end
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/vacations/_form.html.erb
<%= form_for(@vacation) do |f| %>
  <% if @vacation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
      <% @vacation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :tutor_id %><br>
    <%= f.number_field :tutor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacations/edit.html.erb
<h1>Editing vacation</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation %> |
<%= link_to 'Back', vacations_path %>

app/views/vacations/index.html.erb
<h1>Listing vacations</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Tutor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacations.each do |vacation| %>
      <tr>
        <td><%= vacation.start %></td>
        <td><%= vacation.end %></td>
        <td><%= vacation.tutor_id %></td>
        <td><%= link_to 'Show', vacation %></td>
        <td><%= link_to 'Edit', edit_vacation_path(vacation) %></td>
        <td><%= link_to 'Destroy', vacation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacation', new_vacation_path %>

app/views/vacations/new.html.erb
<h1>New vacation</h1>

<%= render 'form' %>

<%= link_to 'Back', vacations_path %>

app/views/vacations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @vacation.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @vacation.end %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @vacation.tutor_id %>
</p>

<%= link_to 'Edit', edit_vacation_path(@vacation) %> |
<%= link_to 'Back', vacations_path %>