config/routes.rb
Rails.application.routes.draw do
  
  resources :cards do
    collection do
      post 'register_card'
      post 'register_bank_account'
      get 'by_user'
      post 'delete_card'
    end
    member do
      post 'activate'
    end
  end

  resources :registered_anomaly_statuses

  resources :registered_anomalies do
    collection do
      post 'from_student'
      post 'from_tutor'
      post 'assign'
      post 'assign_other'
      post 'reject'
    end
  end

  resources :anomalies

  resources :municipalities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :specific_availabilities

  resources :availabilities

  resources :week_days

  resources :vacations

  resources :preferences

  resources :appointment_statuses

  resources :appointments do
    collection do
      get 'by_tutor'
      get 'by_student'
    end
    member do
      post 'change_status'
      post 'force_charge'
      post 'force_pay'
    end
  end

  resources :messages do
    collection do
      get 'conversations'
      get 'by_conversation'
      get 'pending_conversations'
      post 'mark_read'
    end
  end

  resources :reviews do
    collection do
      get 'by_tutor'
    end
    member do
      post 'activate'
    end
  end

  resources :bank_accounts

  resources :categories

  resources :purchases

  resources :addresses

  resources :banks

  resources :states

  resources :cities

  resources :postal_codes

  resources :counties do
    collection do
      get 'find_for_autocomplete'
    end
  end

  resources :students do
    collection do
      get 'profile'
      post 'remember_tutor'
    end
  end

  resources :tutors do
    collection do
      get 'by_county_and_category_ids'
      match 'by_query_params_for_google', :via => [:get, :post]
      get 'profile'
      get 'status'
      get 'by_student'
      get 'balance'
      post 'cash_out'
    end
    member do
      get 'info'
      get 'availability_list'
      get 'ranged_availability_list'
      match 'request_class', :via => [:get, :post]
      match 'save_availabilities', :via => [:get, :post]
      match 'save_specific_availabilities', :via => [:get, :post]
    end
  end

  resources :roles

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords"}
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
    get 'signin', :to => "devise/sessions#new"
    get 'signup', :to => "devise/registrations#new"
  end
  resources :users

  get "counties_all" => "counties#find_for_autocomplete", :as => :find_for_autocomplete

  get "tutor" => "tutor_display#landing", :as => :tutor_landing
  
  get "tutor_redirect" => "tutor_display#redirect", :as => :tutor_redirect

  get "student" => "student_display#landing", :as => :student_landing

  get "tutor_dashboard" => "dashboard#by_tutor", :as => :tutor_dashboard

  get "student_dashboard" => "dashboard#by_student", :as => :student_dashboard

  get "tutor_profile" => "student_display#profile", :as => :tutor_profile
  root 'student_display#landing'

end

app/controllers/appointment_statuses_controller.rb
class AppointmentStatusesController < ApplicationController
  load_and_authorize_resource :except => [:index]

  before_action :set_appointment_status, only: [:show, :edit, :update, :destroy]

  # GET /appointment_statuses
  # GET /appointment_statuses.json
  def index
    @appointment_statuses = AppointmentStatus.all
  end

  # GET /appointment_statuses/1
  # GET /appointment_statuses/1.json
  def show
  end

  # GET /appointment_statuses/new
  def new
    @appointment_status = AppointmentStatus.new
  end

  # GET /appointment_statuses/1/edit
  def edit
  end

  # POST /appointment_statuses
  # POST /appointment_statuses.json
  def create
    @appointment_status = AppointmentStatus.new(appointment_status_params)

    respond_to do |format|
      if @appointment_status.save
        format.html { redirect_to @appointment_status, notice: 'Appointment status was successfully created.' }
        format.json { render :show, status: :created, location: @appointment_status }
      else
        format.html { render :new }
        format.json { render json: @appointment_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_statuses/1
  # PATCH/PUT /appointment_statuses/1.json
  def update
    respond_to do |format|
      if @appointment_status.update(appointment_status_params)
        format.html { redirect_to @appointment_status, notice: 'Appointment status was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment_status }
      else
        format.html { render :edit }
        format.json { render json: @appointment_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_statuses/1
  # DELETE /appointment_statuses/1.json
  def destroy
    @appointment_status.destroy
    respond_to do |format|
      format.html { redirect_to appointment_statuses_url, notice: 'Appointment status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment_status
      @appointment_status = AppointmentStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_status_params
      params.require(:appointment_status).permit(:name)
    end
end

app/helpers/appointment_statuses_helper.rb
module AppointmentStatusesHelper
end

app/views/appointment_statuses/_form.html.erb
<%= form_for(@appointment_status) do |f| %>
  <% if @appointment_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment_status.errors.count, "error") %> prohibited this appointment_status from being saved:</h2>

      <ul>
      <% @appointment_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointment_statuses/edit.html.erb
<h1>Editing appointment_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment_status %> |
<%= link_to 'Back', appointment_statuses_path %>

app/views/appointment_statuses/index.html.erb
<h1>Listing appointment_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment_statuses.each do |appointment_status| %>
      <tr>
        <td><%= appointment_status.name %></td>
        <td><%= link_to 'Show', appointment_status %></td>
        <td><%= link_to 'Edit', edit_appointment_status_path(appointment_status) %></td>
        <td><%= link_to 'Destroy', appointment_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment status', new_appointment_status_path %>

app/views/appointment_statuses/new.html.erb
<h1>New appointment_status</h1>

<%= render 'form' %>

<%= link_to 'Back', appointment_statuses_path %>

app/views/appointment_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment_status.name %>
</p>

<%= link_to 'Edit', edit_appointment_status_path(@appointment_status) %> |
<%= link_to 'Back', appointment_statuses_path %>