config/routes.rb
Rails.application.routes.draw do
  
  resources :cards do
    collection do
      post 'register_card'
      post 'register_bank_account'
      get 'by_user'
      post 'delete_card'
    end
    member do
      post 'activate'
    end
  end

  resources :registered_anomaly_statuses

  resources :registered_anomalies do
    collection do
      post 'from_student'
      post 'from_tutor'
      post 'assign'
      post 'assign_other'
      post 'reject'
    end
  end

  resources :anomalies

  resources :municipalities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :specific_availabilities

  resources :availabilities

  resources :week_days

  resources :vacations

  resources :preferences

  resources :appointment_statuses

  resources :appointments do
    collection do
      get 'by_tutor'
      get 'by_student'
    end
    member do
      post 'change_status'
      post 'force_charge'
      post 'force_pay'
    end
  end

  resources :messages do
    collection do
      get 'conversations'
      get 'by_conversation'
      get 'pending_conversations'
      post 'mark_read'
    end
  end

  resources :reviews do
    collection do
      get 'by_tutor'
    end
    member do
      post 'activate'
    end
  end

  resources :bank_accounts

  resources :categories

  resources :purchases

  resources :addresses

  resources :banks

  resources :states

  resources :cities

  resources :postal_codes

  resources :counties do
    collection do
      get 'find_for_autocomplete'
    end
  end

  resources :students do
    collection do
      get 'profile'
      post 'remember_tutor'
    end
  end

  resources :tutors do
    collection do
      get 'by_county_and_category_ids'
      match 'by_query_params_for_google', :via => [:get, :post]
      get 'profile'
      get 'status'
      get 'by_student'
      get 'balance'
      post 'cash_out'
    end
    member do
      get 'info'
      get 'availability_list'
      get 'ranged_availability_list'
      match 'request_class', :via => [:get, :post]
      match 'save_availabilities', :via => [:get, :post]
      match 'save_specific_availabilities', :via => [:get, :post]
    end
  end

  resources :roles

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords"}
  devise_scope :user do
    get 'logout', :to => "devise/sessions#destroy"
    get 'signin', :to => "devise/sessions#new"
    get 'signup', :to => "devise/registrations#new"
  end
  resources :users

  get "counties_all" => "counties#find_for_autocomplete", :as => :find_for_autocomplete

  get "tutor" => "tutor_display#landing", :as => :tutor_landing
  
  get "tutor_redirect" => "tutor_display#redirect", :as => :tutor_redirect

  get "student" => "student_display#landing", :as => :student_landing

  get "tutor_dashboard" => "dashboard#by_tutor", :as => :tutor_dashboard

  get "student_dashboard" => "dashboard#by_student", :as => :student_dashboard

  get "tutor_profile" => "student_display#profile", :as => :tutor_profile
  root 'student_display#landing'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :tutors
  belongs_to :parent, :foreign_key => "category_id", :class_name => "Category"
  has_many :categories_tutors
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource :except => [:index]

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    if params[:parent] && params[:parent] == 'true'
      @categories = Category.where('category_id is null')
    else
      @categories = Category.all
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :category_id, :picture_url)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :picture_url %><br>
      <%= f.text_field :picture_url %>
    </div>
    <div class="field">
      <%= f.label :category_id %><br>
      <%= f.number_field :category_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture Url</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.picture_url %></td>
        <td><%= category.category_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Picture Url:</strong>
  <%= @category.picture_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.category_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>